### ISSUE TITLE
User story

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/UT-WORKS#1]
Пришли [отсюда](https://github.com/u-transnet/codebase/issues/49)

@EvgeniyPolyakov @jackal1527 @nat-brit @rossul  
Пишем [User Story](https://www.mountaingoatsoftware.com/agile/user-stories), формат - jira, площадка и собственно [таск истории](https://u-trans.atlassian.net/browse/UT-1)

@jackal1527 в jira (см. ссылку на таск истории выше) можно смотреть и дополнять (если будет доступ). В текущем репозитории есть доска [Dashboard](https://github.com/u-transnet/UT-WORKS/projects/1), настроенная аналогично такой же доске в UT-DESIGN у @RomaRAD 

Скилл лучше пока вести на задачах в хабе ИМХО (пока не уясним статус jira и не определимся с площадкой для нее).

**Comment by cptn-solo** [comment]
@jackal1527 @EvgeniyPolyakov @nat-brit @Arteg0r @mparkhomenko @netral23 по [бирже](https://u-trans.atlassian.net/browse/UT-1) можно подключаться в джиру, отладимся, настроимся - так-то в джире конечно побогаче с фичами и возможностями. На примере UT-WORKS, UT-KIT, UT-SСHOOL можно выработать какой-то понятный регламент - что ведется в Jira, а что в хабе.

**Comment by EvgeniyPolyakov** [comment]
БЛОК #24012345

От | eugene-polyakov
Кому | utd-web
Количество | 140.00000 UTDEV.SKILL

до вечера 31.01.18

**Comment by jackal1527** [comment]
Block #24012441

От | eugene-polyakov
Кому | utd-ux
Количество | 200.00000 UTDEV.SKILL

до вечера 31.01.18

**Comment by EvgeniyPolyakov** [comment]
Намечен 1й блок user stories для биржи задач. Результаты итерации в файле https://docs.google.com/spreadsheets/d/1YV06Ygz-zquzZhrhkNmDol8dLJbum5yIyKW-f4_XL6k/edit#gid=0

Уходим в следующую итерацию https://github.com/u-transnet/UT-WORKS/issues/2  для переноса историй в jira с учетом корректировок, озвученных в созвоне.

Можно закрывать

**Comment by cptn-solo** [comment]
@EvgeniyPolyakov 
BLOCK #24029899

TRANSFER |  
-- | --
From | utd-web
To | eugene-polyakov
Quantity | 140.00000 UTDEV

@jackal1527 
BLOCK #24029926

TRANSFER |  
-- | --
From | utd-ux
To | jackal1527
Quantity | 200.00000 UTDEV

Спасибо!
