### ISSUE TITLE
Перенос первых user stories в jira

### ISSUE THREAD

**Issue by EvgeniyPolyakov** [u-transnet/UT-WORKS#2]
Пришли отсюда https://github.com/u-transnet/UT-WORKS/issues/1

Переносим предварительно намеченные user stories по функционалу будущей биржи задач в jira. Формулируем истории с четким, осязаемым результатом.

В тех историях, где видим конкретные таски - создаем задачи.

Смотрим вечером 02.02.18

**Comment by EvgeniyPolyakov** [comment]
БЛОК #24023668

От | eugene-polyakov
Кому | utd-web
Количество | 140.00000 UTDEV.SKILL

До вечера 02.02.18

**Comment by cptn-solo** [comment]
@jackal1527 присоединяйся ;)

**Comment by jackal1527** [comment]
Block #24077430

От | jackal1527
Кому | utd-ux
Количество | 200.00000 UTDEV.SKILL

До вечера 02.02.18

**Comment by EvgeniyPolyakov** [comment]
Создали основные юзер-сторис для всех типов пользователей биржи. По результатам созвона требуется иная организация (модули в виде эпиков, роли в виде лейблов)

Ответственным за направление биржи назначен @jackal1527

Уходим сюда https://github.com/u-transnet/UT-WORKS/issues/3

можно закрывать

**Comment by cptn-solo** [comment]
@jackal1527 
BLOCK #24084191

TRANSFER |  
-- | --
From | utd-ux
To | jackal1527
Quantity | 200.00000 UTDEV

@EvgeniyPolyakov 
BLOCK #24084227

TRANSFER |  
-- | --
From | utd-web
To | eugene-polyakov
Quantity | 140.00000 UTDEV

👍 

Отдельно хотел бы отметить, что в стори вход открыт до вторника. Если кто-то не выскажется - в MVP точно роль не попадет. @u-transnet/crew @u-transnet/partners 
Сейчас описаны роли разработчиков и модераторов (моя). Заказчиков и Инвесторов, как и Голосующих стейкхолдеров - там нет.
