### ISSUE TITLE
Оптимизация user stories в jira

### ISSUE THREAD

**Issue by EvgeniyPolyakov** [u-transnet/UT-WORKS#3]
Пришли отсюда https://github.com/u-transnet/UT-WORKS/issues/2

Реорганизация созданных юзерсторис согласно корректировке после созвона (модули в эпики, роли в лейблы)

Создание и актуализация сторис в разрезе модульного подхода

**Comment by EvgeniyPolyakov** [comment]
БЛОК #24160224

От | eugene-polyakov
Кому | utd-web
Количество | 140.00000 UTDEV.SKILL

до вечера 6.02.18

**Comment by jackal1527** [comment]
Непосредственно работа над задачаей
+
Изучение JIRA и Юзерсториз

Block #24255004
От | jackal1527
Кому | utd-ux
Количество | 400.00000 UTDEV.SKILL

до 8 _02_18

**Comment by EvgeniyPolyakov** [comment]
БЛОК #24272299

От | eugene-polyakov
Кому | utd-web
Количество | 140.00000 UTDEV.SKILL

Добавляем 2 дня скилла к задаче, чтобы не создавать новое иссью. До 8.02.18

**Comment by EvgeniyPolyakov** [comment]
Сделано:

- Созданы модули Bitshares-UI (добработка веб-интерфейса для перессылки скилла), Telegram Bot (голосования и оповещения) и  UT-Works ( будущее направление )
- Созданы user stories  для модулей
- Созданы таски для модуля Bitshares-UI до состояния готовых к запуску в производство

Можно закрывать.

Уходим сюда https://github.com/u-transnet/UT-WORKS/issues/4

**Comment by cptn-solo** [comment]
@EvgeniyPolyakov 
BLOCK #24339198

TRANSFER |  
-- | --
From | utd-web
To | eugene-polyakov
Quantity | 280.00000 UTDEV

@jackal1527 
BLOCK #24339229

TRANSFER |  
-- | --
From | utd-ux
To | jackal1527
Quantity | 400.00000 UTDEV
