### ISSUE TITLE
Оптимизация user stories в jira #4

### ISSUE THREAD

**Issue by jackal1527** [u-transnet/UT-WORKS#4]
Пришли отсюда [ОТСЮДА #3 ](https://github.com/u-transnet/UT-WORKS/issues/3)

Реорганизация созданных юзерсторис согласно корректировке после созвона 
Преобразуем userstories по Эпикам "transnet bot" и "bitshares_UI" в таски и подтаски.
дорабатываем сами userstories

**Comment by EvgeniyPolyakov** [comment]
БЛОК #24256491

От | eugene-polyakov
Кому | utd-web
Количество | 140.00000 UTDEV.SKILL

до 10.02.18

**Comment by jackal1527** [comment]
Block #24272188
От | jackal1527
Кому | utd-ux
Количество | 200.00000 UTDEV.SKILL

до 10 _02_18

**Comment by cptn-solo** [comment]
@EvgeniyPolyakov 
BLOCK #24385475

TRANSFER |  
-- | --
From | utd-web
To | eugene-polyakov
Quantity | 140.00000 UTDEV

@jackal1527 
BLOCK #24385529

TRANSFER |  
-- | --
From | utd-ux
To | jackal1527
Quantity | 200.00000 UTDEV
