### ISSUE TITLE
SPIKE: Исследовать возможности платформы telegram-ботов и github приложений применительно к нашей бирже

### ISSUE THREAD

**Issue by ishmelev23** [u-transnet/UT-WORKS#5]
Задача:
Исследовать возможности платформы telagram-ботов и github приложений применительно к нашей бирже.

Необходимые результат:
Описание функциональных возможностей вышеназванных компонентов и предложения по реализации бота для платформы.

Дата сдачи:
13.02.18 18:00

**Comment by ishmelev23** [comment]
ПЕРЕВОД |  БЛОК #24367609
-- | --
От | superpchelka23
Кому | utd-front
Количество | 62.50000 UTDEV.SKILL
Примечание | https://github.com/u-transnet/UT-WORKS/issues/5 SPIKE: Исследовать возможности платформы telagram-ботов и github приложений применительно к нашей бирже 13.02.18 18:00

**Comment by ishmelev23** [comment]
Для автоматизации на необходимо в task-менеджере организовать следующую информацию:
 - исполнитель;
 - арбитры;
 - скилл;
 - дата сдачи;

Фактически есть 2-е модели реализации:
1) Использовать GitHub.
Создание коммента с кастомной разметкой.
С помощью api слушать ленту issues и реагировать на те или иные комменты.
Явный минус в данном случае это огромный человеческий фактор в плане написания разметки и ошибок ввода.
2) Использовать Jira, как основу, но отражать информацию по задачам в GitHub.
В Jira на задачу может быть добавлен исполнитель.
Могут быть назначены наблюдатели.
Основное преимущество Jira в этом плане, что Jira имеет конструктор форм и мы можем настроить необходимость ввода всей необходимой информации по задаче.
Какую именно информацию отражать в GitHub необходимо согласовать.

-------------------

GitHub приложения
Фактически это подключение бота, который работает от имени организации или юзера, без создания отдельного аккаунта под него.

-------------------

Что может Telegram?

Фактически всё что нам необходимо есть:
 - отправка сообщений в личку или в публичный чат;
 - обработка кастомных комманд к боту;
 - инлайн кнпоки - это кнопки, которые крепятся к сообщениям 
 - webhook;

Из интересных фишек, которые можно использовать это:
 - изменение текста в статус-бар у бота (туда где обычно у пользователя пишется "Печатает.." можно писать свой текст);
 - добавление инлайнов (вызов бота непосредственно из диалога с человеком), которые позволяют искать и выбирать данные еще в момент ввода сообщения;
 - клавиатуры - это возможность записать команды в виде кнопок, которые отображаются под полем ввода вместо обычной клавиатуры;

**Comment by cptn-solo** [comment]
@netral23 открывабельные URL-ссылки мы же тоже можем формировать ? для упрощения перехода в блокчейн-GUI с подстановкой значений

**Comment by ishmelev23** [comment]
@kkrupovich и не просто ссылки, мы можем сделать кнопки при клике на который будут открываться ссылки.

**Comment by cptn-solo** [comment]
@netral23 @EvgeniyPolyakov @jackal1527 тогда, видимо, как-то так ? :
1. исполнитель объявляет работу выполненной - это создает proposal с учетки бюджетной позиции в адрес исполнителя (настройки) **ссылка на создание proposal**
2. арбитры (включены в мультиподпись учетки бюджетной позиции) оценивают результат и подтверждают предложение  **ссылка на подтверждение proposal**
3. после получения необходимого количества подтверждений транзакция финализируется, исполнитель получает оплату **listener бота, либо блокчейна**
4. факт оплаты запускает процесс отчетности - в jira/github фиксируется блок и атрибуты транзакции возмещения **скрипт, запускаемый из listener'а**

В общем, наша задача - уйти от абсолютной небходимости в участии "бухгалтера". Вы же понимаете, что, например, если веса будут настроены таким образом:
* бухгалтер = 5
* арбитр1 = 2
* арбитр2 = 2
* арбитр3 = 2

а treshold будет выставлен в 6, то достаточно будет бухгалтера и любого из арбитров, либо консенсуса между арбитрами, для того, чтобы задача была оплачена

**Comment by ishmelev23** [comment]
Осталось решить 2-а момента:
1) Как сделать так, чтобы у исполнителя при инициации proposal автоматически за этим proposal закреплялись арбитры связанные с этой задачей.
2) И соответственно из задачи выше встаёт вопрос, как сделать связку между аккаунтом в Jira/GitHub  и учеткой на платформе с наименьшими затратами.

**Comment by cptn-solo** [comment]
@netral23 
> Как сделать так, чтобы у исполнителя при инициации proposal автоматически за этим proposal закреплялись арбитры связанные с этой задачей.

учетки арбитров - это учетки, включенные в мультиподпись бюджетной позиции, в рамках которой производится компенсация скилла. Вопрос тут скорее в том, что у всех зарегистрированных в боте арбитров должна быть указана их учетка в блокчейне (как и у исполнителей, впрочем) - т.о. можно рассмотреть пример, который вообще будет брать арбитрами именно учетки из настроек мультиподписи по блокчейну (что правильно)

> И соответственно из задачи выше встаёт вопрос, как сделать связку между аккаунтом в Jira/GitHub и учеткой на платформе.

регистрация в боте - это увязка телеграм/jira/github/bitshares(transnet - позже)

**Comment by cptn-solo** [comment]
@netral23 предлагаю переходить к проектированию в Jira ([стори и подзадачи](https://u-trans.atlassian.net/browse/UW-34)), в хабе создадим реп для кода бота, задачи в хабе предлагаю ограничить feature-реквестами,  баг-репортами и пулл-реквестами, причем задачи в хабе можно связывать с Jira.
Jira тут нужна для проектирования, т.к. будет очень много пересечений между модулями (Bitshares-UI/works-bot/works-web/school-web/school-bot) + общий дизайн и планирование

BLOCK #24401892

TRANSFER |  
-- | --
From | utd-front
To | superpchelka23
Quantity | 62.50000 UTDEV
