### ISSUE TITLE
Оптимизация user stories в jira

### ISSUE THREAD

**Issue by jackal1527** [u-transnet/UT-WORKS#6]
Пришли отсюда [ОТСЮДА #4](https://github.com/u-transnet/UT-WORKS/issues/4)

Реорганизация созданных юзерсторис согласно корректировке после созвона
Преобразуем userstories по Эпикам "transnet bot" и "bitshares_UI" в таски и подтаски.
дорабатываем сами userstories

+ начало работы по UT-SCHOOL

**Comment by jackal1527** [comment]
Далее переходим в [JIRA](https://u-trans.atlassian.net/browse/UT-90)

Block #24439183
От | jackal1527
Кому | utd-ux
Количество | 200.00000 UTDEV.SKILL

до 14 _02_18

**Comment by cptn-solo** [comment]
@jackal1527 
BLOCK #24444361

TRANSFER |  
-- | --
From | utd-ux
To | jackal1527
Quantity | 200.00000 UTDEV
